image: multiarch/debian-debootstrap

arches:
  - armhf
  - arm64

targets:
  - jessie

env:
  - DOCKER_DOWNLOAD=https://releases.rancher.com/install-docker
  - DOCKER_VERSION=18.06
  - DOCKER_BIN=/home/$username/$username/bin/docker
  - DOCKER_COMPOSE_DOWNLOAD= https://github.com/docker/compose/releases/download
  - DOCKER_COMPOSE_VERSION=1.22.0
  - DOCKER_COMPOSE_BIN=/home/$username/bin/docker-compose

before_install:
  - echo "==> Welcome to redelivre/qemu-"`uname -m`
  - echo "$(whoami) at $(pwd) on $(uname -a)"
  - apt-get install git curl python python-pip
  - export DOCKER_COMPOSE_ARCH="docker-compose-"`uname -s`"-"`uname -m`

install:
  - curl $DOCKER_DOWNLOAD/$DOCKER_VERSION.sh -o $DOCKER_BIN
  - curl -L $DOCKER_COMPOSE_DOWNLOAD/$DOCKER_COMPOSE_VERSION/$DOCKER_COMPOSE_ARCH -o $DOCKER_COMPOSE_BIN
    
after_install:
  - chmod +x /home/$username/bin/docker
  - chmod +x /home/$username/bin/docker-compose

before_script:
  - git clone --branch=aarch64 https://www.github.com/lunhg/alpine /home/$username/alpine
  
script:
  - docker-compose --project-directory=/home/$username/alpine -d --build

after_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose --project-directory=/home/$username/alpine push alpine
  
after_success:
  - docker-compose --project-directory=/home/$username/alpine ps alpine
  - docker-compose --project-directory=/home/$username/alpine logs alpine
  
