image: multiarch/debian-debootstrap

arches:
  - armhf
  - arm64

targets:
  - jessie

env:
  - DOCKER_VERSION=18.06
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - echo "==> Welcome to redelivre/qemu"
  - echo "$(whoami) at $(pwd) on $(uname -a)"
  - apt-get install git curl python python-pip
    
install:
  - curl https://releases.rancher.com/install-docker/$DOCKER_VERSION.sh | sh > /home/$username/bin/docker
  - curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` > /home/$username/bin/docker-compose
    
after_install:
  - chmod +x /home/$username/bin/docker
  - chmod +x /home/$username/bin/docker-compose

before_script:
  - git clone --branch=aarch64 https://www.github.com/lunhg/alpine /home/$username/alpine
  
script:
  - docker-compose --project-directory=/home/$username/alpine -d alpine

after_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose --project-directory=/home/$username/alpine push alpine
  
after_success:
  - docker-compose --project-directory=/home/$username/alpine ps alpine
  - docker-compose --project-directory=/home/$username/alpine logs alpine
  
