image: multiarch/debian-debootstrap

arches:
  - armhf
  - arm64

targets:
  - jessie

env:
  - REPO=lunhg/alpine
  - BRANCH=aarch64
  - DOCKER_DOWNLOAD=https://releases.rancher.com/install-docker
  - DOCKER_VERSION=18.06
  - DOCKER_COMPOSE_DOWNLOAD= https://github.com/docker/compose/releases/download
  - DOCKER_COMPOSE_VERSION=1.23.1

before_install:
  - uname -a
  - whoami
  - hostname
  - pwd
  - apt-get update
  - echo "y" | apt-get install git curl python python-pip

install:
  - whoami
  - pwd
  - curl $DOCKER_DOWNLOAD/$DOCKER_VERSION.sh | sh >> /home/$username/bin/docker
  - curl -L $DOCKER_COMPOSE_DOWNLOAD/$DOCKER_COMPOSE_VERSION/run.sh | sh >> /home/$username/bin/docker-compose
    
after_install:
  - chmod +x /home/$username/bin/docker
  - chmod +x /home/$username/bin/docker-compose
  - export PATH=$PATH:/home/$username/bin

before_script:
  - echo $REPO | sed -E 's|(.+)/(.+)|/home/\$$username/\1|g' | mkdir 
  - git clone --branch=$BRANCH https://www.github.com/$REPO /home/$username/$REPO
  
script:
  - docker-compose --project-directory=/home/$username/alpine -d --build

after_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose --project-directory=/home/$username/alpine push alpine
  
after_success:
  - docker-compose --project-directory=/home/$username/alpine ps alpine
  - docker-compose --project-directory=/home/$username/alpine logs alpine
  - echo "y" | docker-compose system prune -a
  
