image: multiarch/debian-debootstrap

arches:
  - arm64

targets:
  - jessie

volumes:
  - $HOME/bin:$HOME/bin

env:
  - REPO=lunhg/alpine
  - BRANCH=aarch64
  - GITHUB=https://www.github.com
  - DOCKER_DOWNLOAD=https://releases.rancher.com/install-docker
  - DOCKER_VERSION=18.06
  - DOCKER_COMPOSE_DOWNLOAD= https://github.com/docker/compose/releases/download
  - DOCKER_COMPOSE_VERSION=1.23.1

# User is root
before_install:
  - echo "before_install:" && echo "==> user: $(whoami)" && echo "==> home: $HOST" && echo "==> os: $(uname -a)" && echo ==> "==> host: $(hostname)"
  - apt-get update
  - apt-get install -y git curl python

# User isnt root on this point
install:
  - echo "install:" && echo "==> user: $(whoami)" && echo "==> home: $HOST" && echo "==> os: $(uname -a)" && echo ==> "==> host: $(hostname)"
  - mkdir $HOME/bin
  - curl $DOCKER_DOWNLOAD/$DOCKER_VERSION.sh | sh >> $HOME/bin/docker
  - curl -L $DOCKER_COMPOSE_DOWNLOAD/$DOCKER_COMPOSE_VERSION/run.sh | sh >> $HOME/bin/docker-compose
    
after_install:
  - echo "after_install:" && echo "==> user: $(whoami)" && echo "==> home: $HOST" && echo "==> os: $(uname -a)" && echo ==> "==> host: $(hostname)"
  - for i in "docker" "docker-compose" ; do chmod +x $HOME/bin/$i ; done
  - export PATH=$PATH:$HOME/bin

before_script:
  - echo "before_script:" && echo "==> user: $(whoami)" && echo "==> home: $HOST" && echo "==> os: $(uname -a)" && echo ==> "==> host: $(hostname)"
  - echo $REPO | sed -E 's|(.+)/(.+)|$HOME/\1|g' | mkdir
  - git clone --branch=$BRANCH $GITHUB/$REPO $HOME/$REPO
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - echo "script:" && echo "==> user: $(whoami)" && echo "==> home: $HOST" && echo "==> os: $(uname -a)" && echo ==> "==> host: $(hostname)"
  - docker-compose up --project-directory=$HOME/$REPO
  - docker-compose ps --project-directory=$HOME/$REPO
  - docker-compose logs --project-directory=$HOME/$REPO

after_script:
  - echo "after_script: $(whoami) on $PWD at $(uname -a)"
  - docker-compose push --project-directory=$HOME/$REPO
