language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu

env:
    global:
      - QEMU_ARCHES=aarch64 QEMU_VERSION=3.0.0 DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - make install

script:
  - make build
  - make print

after_success:
  - make push

# don't notify me when things fail
notifications:
  email: false
