language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

services:
  - docker
  - docker-compose

cache:
  directories:
    - $HOME/qemu

env:
  global:
    - QEMU_ARCHES=aarch64 QEMU_VERSION=3.0.0

before_install:
  - make build

before_script:
  - make install
  - make after_install
  - make before_script

script:
  - make script

after_success:
  - make after_success

# don't notify me when things fail
notifications:
  email: false
