language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu

before_install:
  - make before_install
  
install:
  - make install

after_install:
  - make after_install

before_script:
  - make before_script

script:
  - make script

after_script:
  - make after_script

after_success:
  - echo "DONE!"

# don't notify me when things fail
notifications:
  email:
    false
