language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu

before_install:
  - make build
  - make docker
  - make before_install
  
before_script:
  - make install
  - make after_install

script:
  - make before_script
  - make script

after_success:
  - make after_success

# don't notify me when things fail
notifications:
  email:
    false
