language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu

env:
    global:
      - QEMU_VERSION=v2.12.0
      - QEMU_ARCHES="aarch64"
      - DOCKER_COMPOSE_VERSION=1.22.0


before_install:
  - curl -L https://raw.githubusercontent.com/jdub/travis-qemu/master/travis-qemu.sh -o travis-qemu.sh
  - chmod +x travis-qemu.sh
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker -v
  - docker-compose -v

before_script:
  - bash -e travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin

script:
  - qemu-aarch64 docker-compose up -d alpine
  - qemu-aarch64 docker-compose ps alpine
  - qemu-aarch64 docker-compose logs alpine

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose push alpine

# don't notify me when things fail
notifications:
  email: false
