language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu
    - $HOME/bin

script:
  - make all

# don't notify me when things fail
notifications:
  email: false
