sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.22.0

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - docker-compose -v
  - docker -v

script:
  - docker-compose up -d alpine
  - docker-compose ps alpine
  - docker-compose logs alpine
  - docker-compose push alpine
