language: bash

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/qemu

before_install:
  - make clean
  - make before_install
  
install:
  - make install

after_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

before_script:
  - make before_script

script:
  - make script

# don't notify me when things fail
notifications:
  email: false
